sudo: false
language: node_js
node_js:
  - "8"

before_install: rm -f package-lock.json
install: npm install

cache:
  directories:
  - node_modules

branches:
  only:
  - master

script:
  npm run test && npm run docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master